def fail_func():
    raise Exception("just a failure")
